language: ruby

# before_script: 'bundle exec appraisal install'
script: 'bundle appraisal rake test'

rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head

matrix:
  allowed_failures:
    - rvm: ruby-head
    - rvm: jruby-head

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
