language: ruby

script: 'bundle exec rake test'

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx
  - ruby-head
  - jruby-19mode
  - jruby-head

matrix:
  allowed_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
