language: ruby

before_script: 'bundle exec appraisal install'
script: 'appraisal rake test'

rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-1.6.8
  - jruby-1.7.6
  - jruby-head
  - rbx-2.0.0
  - rbx-2.1.1
  - rbx-head

matrix:
  allowed_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-head

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
